#!/bin/sh
sxhkd &	# Bind keys
# Switch to US international with Caps as Mod/Escape
setxkbmap -option caps:super -variant altgr-intl && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
dunst &			# dunst for notifications
mpdupdate
nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[3]=500' &
nvidia-settings -a '[gpu:0]/GraphicsClockOffset[3]=150' &
wal --theme base16-oceanicnext

[ -f "$HOME/.xprofile" ] && . ~/.xprofile

lutris &
exec i3
